// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqDdVvgxyjTBiaMAoM9HiLWkK2rL6mku0',
    appId: '1:147716726105:android:e508d011d4b801d74c4048',
    messagingSenderId: '147716726105',
    projectId: 'kpct-radio-app',
    storageBucket: 'kpct-radio-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlm1251v9Dfh33fFJeFS8TrAerT6Cp8kc',
    appId: '1:147716726105:ios:920527c26c88d6174c4048',
    messagingSenderId: '147716726105',
    projectId: 'kpct-radio-app',
    storageBucket: 'kpct-radio-app.firebasestorage.app',
    iosBundleId: 'com.kpct.dao.radioApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmxBFq5KaIulJUIiTZ-g_HiK6y6Zirj-0',
    appId: '1:147716726105:web:deee05d52eb6a81b4c4048',
    messagingSenderId: '147716726105',
    projectId: 'kpct-radio-app',
    authDomain: 'kpct-radio-app.firebaseapp.com',
    storageBucket: 'kpct-radio-app.firebasestorage.app',
  );

}